server:
    port: 9669
spring:
    application:
        name: foo-web
    cloud:
        compatibility-verifier:
            enabled: false
        sentinel:
            transport:
                dashboard: localhost:8080
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        # 连接池
        hikari:
            #连接池名
            pool-name: DateHikariCP
            #最小空闲连接数
            minimum-idle: 10
            # 空闲连接存活最大时间，默认600000（10分钟）
            idle-timeout: 180000
            # 连接池最大连接数，默认是10
            maximum-pool-size: 60
            # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
            auto-commit: true
            # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
            max-lifetime: 1800000
            # 数据库连接超时时间,默认30秒，即30000
            connection-timeout: 50000
            connection-test-query: SELECT 1
        password: root
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/sentinel?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
        username: root
    main:
        allow-bean-definition-overriding: true
        allow-circular-references: true
